version: "3.7"

services:
  gui:
    image: lnvortex/vortex-gui:master
    user: 0:1000
    restart: on-failure
    stop_grace_period: 1m
    environment:
      rpcUrl: "http://vortexd:12522"
      rpcUser: "user"
      rpcPassword: $APP_PASSWORD
    ports:
      - "3000:3000"
    depends_on:
      - vortexd
  vortexd:
    image: lnvortex/vortexd:0.0.0-387-ae87716a-SNAPSHOT@sha256:6f1ee215f74600a401b6112ed112065ccd084ecbf4dce5a7063cc5cb9bd079a0
    entrypoint: ["/opt/docker/bin/vortexd", "--datadir", "/ln-vortex", "--conf", "/opt/docker/docker-application.conf"]
    user: 0:1000
    restart: on-failure
    volumes:
      - ./data/wallet:/ln-vortex
      - ${HOME}/.lnd:/lnd:ro
    environment:
      BITCOIN_S_NETWORK: "testnet3"

      BITCOIN_S_TOR_PROVIDED: "true"
      BITCOIN_S_TOR_ENABLED: "false"
      BITCOIN_S_PROXY_ENABLED: "true"
      BITCOIN_S_SOCKS5_PROXY: "tor:9050"

      VORTEX_RPC_USER: "user"
      VORTEX_RPC_PASSWORD: $APP_PASSWORD

      VORTEX_LND_RPC_URI: "$APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_GRPC_PORT"
      VORTEX_LND_DATADIR: "/lnd/"
    ports:
      - "2522:2522"
      - "12522:12522"
      - "22522:22522"
      - "32522:32522"
    # to connect to locally running lightning node
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - tor
  tor:
    image:  bitcoinscala/tor:latest
    entrypoint: ["/tor", "--ExitRelay", "0", "--BridgeRelay",  "0", "--SOCKSPort", "0.0.0.0:9050", "--ControlPort", "0.0.0.0:9051", "--HashedControlPassword", "16:EF3A794FD6F30EF76049147EF252111809E7D51C049FEB353B547C1553"]
    restart: on-failure
