name: Postgres Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: "! contains(github.event.pull_request.labels.*.name, 'documentation')"
    env:
      PG_ENABLED: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: zulu@1.11
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-cache
      - name: Run postgres tests
        run: sbt downloadBitcoind downloadLnd serverTest/test clientTest/test clientServerTest/test
